### ISSUE TITLE
SiaNet.Examples.CPUOnly Error in new version

### ISSUE THREAD

**Issue by sharpwood** [deepakkumar1984/SiaNet#10]
![qq 20171122094620](https://user-images.githubusercontent.com/7440304/33105848-4b31498a-cf6a-11e7-847c-1a85d8ebc805.png)

**Comment by deepakkumar1984** [comment]
Fixed the issue. Please take the latest version and try now!

Thanks,
Deepak

**Comment by sharpwood** [comment]
Great！
