### ISSUE TITLE
InvalidCastException

### ISSUE THREAD

**Issue by ZhangFinder** [deepakkumar1984/SiaNet#13]
1;  class Sequential : Evaluate(Value data) ,
2  class DataFrameTrainPredict: Evaluate(object testData)
 Sequential .Evaluate invokes DataFrameTrainPredict.Evaluate,and in DataFrameTrainPredict.Evaluate there are "DataFrame data = (DataFrame)testData;" , so  it is a InvalidCastException when Value  is  Cast into DataFrame.

**Comment by deepakkumar1984** [comment]
I have checked in the fix. Could you please take latest and try again.

**Comment by ZhangFinder** [comment]
You have  changed "Sequential . Evaluate(Value data)" into "Sequential .Evaluate(DataFrame data)" , Have you considered about "ImgGenTrainPredict.Evaluate(object testData)"?  In "ImgGenTrainPredict.Evaluate(object testData)" ,there is "Value data = (Value)testData;" ,and "ImgGenTrainPredict.Evaluate" may also be invoked by "Sequential . Evaluate"

**Comment by deepakkumar1984** [comment]
I am working on standardizing the dataframe. There is another ImageDataFrame which is inherited from the XYFrame class but its not completed yet. If we need to predict with images please wait this week for me to complete the code and test it out. I will setup some examples for you on how to use it.

**Comment by ZhangFinder** [comment]
Thank you
