### ISSUE TITLE
Model.evaluate error on softmax

### ISSUE THREAD

**Issue by nikosdim1** [deepakkumar1984/SiaNet#17]
Model.evaluate does not return full softmax array to get the index of the predicted class. It only returns value. 
eg. in a multiclass prediction model.evaluate, expected is : (0.10, 0,05, 0,85) so the winner is 3d value but it returns only the single value of 0.85

**Comment by deepakkumar1984** [comment]
Need to work on this.

**Comment by deepakkumar1984** [comment]
Can you please check now if you are getting all array.
