### ISSUE TITLE
Shuffle addition on training

### ISSUE THREAD

**Issue by nikosdim1** [deepakkumar1984/SiaNet#18]
It would be nice to have a shuffle option on each epoch while Model.Train

**Comment by deepakkumar1984** [comment]
Bit tricky, because I have a shuffle method on DataFrame and training happens in XYFrame. Need to be careful while writing shuffle in XYFrameto map correct X to Y

**Comment by deepakkumar1984** [comment]
Shuffle implementedwhile training
