### ISSUE TITLE
Server for downloading example datasets could not be resolve.

### ISSUE THREAD

**Issue by mctheaw** [deepakkumar1984/SiaNet#30]
Hi,

When SiaNet downloads the example datasets, it always show error message "System.Net.WebException: The remote name could not be resolve: 'sianet.blob.core.windows.net'" (Line 182 in Downloader.cs file).

Please let me know where I can find all example datasets.

Thank you.

**Comment by deepakkumar1984** [comment]
Yeah the azure subscription expired. Did not pay my bills :)

Will try to restore this ASAP. Sorry for the inconvenience.

**Comment by deepakkumar1984** [comment]
Fixed. Paid the bills :)
