### ISSUE TITLE
Error using Accuracy metric on the timeseries example

### ISSUE THREAD

**Issue by linkerro** [deepakkumar1984/SiaNet#31]
I've tried using the Accuracy metric on the TimeSeriesPrediction example and I get an error caused by the fact that Predictions variable has 1 dynamic axis while the Labels variable has 2 dynamic axes.

    System.ApplicationException: Operation 'TransposeTimes': Operand 'Output('Hardmax571_Output_0', [1], [#])' has dynamic axes, that do not match the dynamic axes '[*, #]' of the other operands.

Is this a bug or is this intended behavior?

**Comment by deepakkumar1984** [comment]
Time series prediction is kind of regression so MSE is being used. Here is an answer on how to calculate accuracy for your reference. https://stats.stackexchange.com/questions/114752/forecast-accuracy-calculation
