### ISSUE TITLE
Examples for creating datasets?

### ISSUE THREAD

**Issue by neopedro** [deepakkumar1984/SiaNet#8]
Hello, awesome project, I was checking the examples, I don't know how to construct datasets, could make a feed forward neural network to solve the XOR problem and showing how to construct dataset? That'd would be very helpful though. Thanks.

**Comment by deepakkumar1984** [comment]
Thanks mate! I am working on improvising the dataframe class to make it simpler. I will create a wiki on how to use it. Please feel to add more feedback which will help me improve this project.

**Comment by neopedro** [comment]
Thanks for the reply.

**Comment by deepakkumar1984** [comment]
I created a WIKI and sample code in the example to build XOR dataset and train them using simple network.

https://github.com/deepakkumar1984/SiaNet/wiki/Example-Build-Dataset---XOR-Gate
